resources:
  - url: http://127.0.0.1:5000/logbook-card.js
    type: module
views:
  - cards:
      - type: custom:logbook-card
        name: Logbook Card Development
        entity: sun.sun
        test_gui: true
